version: "3"

services:

# PRODUCTION
  ssh-server:
    build:
      context: ./
      dockerfile: Dockerfile_luxopenssh
    image: pam-ssh-server:latest
    restart: always
    ports:
      - "2222:22"
